# Generated by Django 5.0.4 on 2024-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudApp", "0003_alter_studentdetails_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="gender",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
