# Generated by Django 5.0.4 on 2024-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudApp", "0004_alter_studentdetails_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="gender",
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
